# Generated by Django 5.1.6 on 2025-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfcuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
