# Generated by Django 5.1.6 on 2025-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_cfcuser_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='amount_approved',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Info Required', 'Info Required'), ('Approved', 'Approved'), ('Partially Approved', 'Partially Approved'), ('Denied', 'Denied'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
