# Generated by Django 5.1.6 on 2025-03-13 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_bill_approved_request_amount_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfcuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Requester', 'Requester')], default='Requester', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
