# Generated by Django 5.1.6 on 2025-03-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_cfcuser_user_type_approvedusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApprovedUsers',
            new_name='ApprovedUser',
        ),
    ]
