# Generated by Django 5.1.6 on 2025-03-13 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_rename_approvedusers_approveduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveduser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='approveduser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='approveduser',
            name='user',
        ),
        migrations.AddField(
            model_name='approveduser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='approveduser',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cfcuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
