# Generated by Django 5.1.6 on 2025-03-14 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_remove_approveduser_id_remove_approveduser_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='approved_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='approveduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approveduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
