# Generated by Django 5.1.6 on 2025-03-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_rename_approved_at_approval_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfcuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='approveduser',
            name='signed_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cfcuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cfcuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
